name: root
channels:
- conda-forge
- defaults
- nodefaults
dependencies:
- pyyaml
- sqlalchemy
- python-dateutil
- jsonschema
- cachetools
- coveralls
- numpy
- numexpr # For AE/EE
- rasterio
- singledispatch
- netcdf4 
- psycopg2
- gdal
- dask
- xarray
- redis-py # redis client lib, used by celery
- redis # redis server
- pep8 # testing
- fiona # movie generator app
- mock # testing
- hypothesis # testing
- matplotlib # pixel drill app
- pathlib
- compliance-checker
- boto3 = 1.4.3
- pathos
- zstandard
- compliance-checker = 3.0.3
- cython # used by netcdf4 at compile only, but needed for compliance checker to load plugins
- pygeoif = 0.6 # compliance-checker 3.0.3 fails with 0.7
- paramiko # for simple-replicas
- sshtunnel # for simple-replicas
- tqdm # for simple-replicas
- pip:
  - celery >= 4
  - pypeg2
  - pylint == 1.7.2 # testing  
  - SharedArray
  - yamllint # testing
